### ISSUE TITLE
Creating new entity from control panel does not show proper message when there is existing entity with the same code

### ISSUE THREAD

**Issue by binis2** [nemesis-software/nemesis-support#24]
When you try to create new entity from control panel (in our case widget) if the code already exists there is a message "Entity successfully saved" thou it is not. 

Tracing the browser's network log doesn't show any errors except one (404) when the data of the new entity is requested from the browser. There is no error in the log either so I assume that there is custom logic involved in the process.

Regards,
Binis

**Comment by ptahchiev** [comment]
As this has been explained by @TeodorTunev it is a known issue with SpringData and you need to update your version of spring-data-rest.

**Comment by MHSF** [comment]
Здравей, Петър, има ли workaround, тъй като новата версия е най-рано м.декември?

**Comment by ptahchiev** [comment]
Hello, you can update the spring-data stack by overriding the release train property like so:
````
<spring-data-releasetrain.version>Ingalls-BUILD-SNAPSHOT</spring-data-releasetrain.version-->
````
to whatever version suits you best.

**Comment by binis2** [comment]
Unfortunately this doesn't help. Increasing version above Ingalls-SR4 makes our version of the nemesis project to crash at startup with 

`
java.lang.NoSuchMethodError: org.springframework.data.repository.config.AnnotationRepositoryConfigurationSource.<init>(Lorg/springframework/core/type/AnnotationMetadata;Ljava/lang/Class;Lorg/springframework/core/io/ResourceLoader;Lorg/springframework/core/env/Environment;)V
        at org.springframework.boot.autoconfigure.data.AbstractRepositoryConfigurationSourceSupport$1.<init>(AbstractRepositoryConfigurationSourceSupport.java:67)
        at org.springframework.boot.autoconfigure.data.AbstractRepositoryConfigurationSourceSupport.getConfigurationSource(AbstractRepositoryConfigurationSourceSupport.java:66)
        at org.springframework.boot.autoconfigure.data.AbstractRepositoryConfigurationSourceSupport.registerBeanDefinitions(AbstractRepositoryConfigurationSourceSupport.java:58)
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsFromRegistrars(ConfigurationClassBeanDefinitionReader.java:354)
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:143)
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:116)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:320)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:228)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:270)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:93)
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:687)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:525)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
        at bg.vivacom.commerce.VivacomApplication.main(VivacomApplication.java:39)
`

**Comment by ptahchiev** [comment]
As discussed this issue is because of sring-data-ingalls-SR7 requires spring-boot 1.5.7.RELEASE. You need to update the spring-boot dependencies as well.

**Comment by ptahchiev** [comment]
I am closing this issue as resolved.
