### ISSUE TITLE
Bug: cannot init ORACLE database after upgrade to v1.5.1.RELEASE

### ISSUE THREAD

**Issue by tttodorov13** [nemesis-software/nemesis-support#8]
While init via command line in Ubuntu 16.04 LTS (mvn nemesis:init-db -Dprofiles=oracle) the following Error is produced:
[ERROR] Migration of schema "<schema_name>" to version <project_name> - init failed! Please restore backups and roll back database and code!
[ERROR] 
Migration <project_name><project_version>__init.sql failed
-------------------------------------
SQL State  : 42000
Error Code : 2261
Message    : ORA-02261: such unique or primary key already exists in the table
Location   : db/migration/oracle/<project_name><project_version>__init.sql (/home/<user_name>/<project_workspace_name>/target/classes/db/migration/oracle/<project_name><project_version>__init.sql)
Line       : 2735
Statement  :     alter table search_facet_slider_profile 
        add constraint UK_djimpo6hx6att9tflgcfi5a8w unique (id)

org.flywaydb.core.internal.dbsupport.FlywaySqlScriptException: 
Migration <project_name><project_version>__init.sql failed
-------------------------------------
SQL State  : 42000
Error Code : 2261
Message    : ORA-02261: such unique or primary key already exists in the table
Location   : db/migration/oracle/<project_name><project_version>__init.sql (/home/<user_name>/<project_workspace_name>/target/classes/db/migration/oracle/<project_name><project_version>__init.sql)
Line       : 2735
Statement  :     alter table search_facet_slider_profile 
        add constraint UK_djimpo6hx6att9tflgcfi5a8w unique (id)

	at org.flywaydb.core.internal.dbsupport.SqlScript.execute(SqlScript.java:117)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:71)
	at org.flywaydb.core.internal.command.DbMigrate.doMigrate(DbMigrate.java:352)
	at org.flywaydb.core.internal.command.DbMigrate.access$1100(DbMigrate.java:47)
	at org.flywaydb.core.internal.command.DbMigrate$4.doInTransaction(DbMigrate.java:308)
	at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72)
	at org.flywaydb.core.internal.command.DbMigrate.applyMigration(DbMigrate.java:305)
	at org.flywaydb.core.internal.command.DbMigrate.access$1000(DbMigrate.java:47)
	at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:230)
	at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:173)
	at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:173)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:959)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:917)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1373)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:917)
	at com.nemesis.platform.core.service.platform.impl.PlatformServiceImpl.lambda$initializeDatabase$0(PlatformServiceImpl.java:299)
	at com.nemesis.platform.core.service.platform.impl.PlatformServiceImpl.withDataMigrations(PlatformServiceImpl.java:442)
	at com.nemesis.platform.core.service.platform.impl.PlatformServiceImpl.withDataMigrations(PlatformServiceImpl.java:436)
	at com.nemesis.platform.core.service.platform.impl.PlatformServiceImpl.initializeDatabase(PlatformServiceImpl.java:297)
	at com.nemesis.platform.core.service.platform.impl.PlatformServiceImpl$$FastClassBySpringCGLIB$$21eaf515.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:669)
	at com.nemesis.platform.core.service.platform.impl.PlatformServiceImpl$$EnhancerBySpringCGLIB$$e13dd82e.initializeDatabase(<generated>)
	at com.nemesis.maven.plugin.platform.init.InitPlatformDbMojo.doExecute(InitPlatformDbMojo.java:36)
	at com.nemesis.maven.plugin.mojo.AbstractNemesisPlatformMojo.execute(AbstractNemesisPlatformMojo.java:88)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.sql.SQLSyntaxErrorException: ORA-02261: such unique or primary key already exists in the table

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:494)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:446)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1054)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:623)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:252)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:612)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:213)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:37)
	at oracle.jdbc.driver.T4CStatement.executeForRows(T4CStatement.java:896)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1119)
	at oracle.jdbc.driver.OracleStatement.executeInternal(OracleStatement.java:1737)
	at oracle.jdbc.driver.OracleStatement.execute(OracleStatement.java:1692)
	at oracle.jdbc.driver.OracleStatementWrapper.execute(OracleStatementWrapper.java:300)
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95)
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
	at org.flywaydb.core.internal.dbsupport.JdbcTemplate.executeStatement(JdbcTemplate.java:238)
	at org.flywaydb.core.internal.dbsupport.SqlScript.execute(SqlScript.java:114)
	... 47 more
Caused by: Error : 2261, Position : 97, Sql =     alter table search_facet_slider_profile 
        add constraint UK_djimpo6hx6att9tflgcfi5a8w unique (id), OriginalSql =     alter table search_facet_slider_profile 
        add constraint UK_djimpo6hx6att9tflgcfi5a8w unique (id), Error Msg = ORA-02261: such unique or primary key already exists in the table

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:498)
	... 63 more

**Comment by ptahchiev** [comment]
Hello Toshko,
thank you for this bug-fix - it has been resolved as a hotfix. Please confirm it is working fine now.

**Comment by tttodorov13** [comment]
Hello Petar,
I confirm it is working fine now.

**Comment by ptahchiev** [comment]
OK, I'm closing this issue.
